POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço",
    "description": "Algum descrição",
    "price": "1400",
    "image": "https://www.ifsc.edu.br/documents/1920563/3622212/ifsc_verifica_telemedicina-05.jpg/340b440f-8dbe-400b-b61c-dfbcd7b1983d?t=1632854865119"
}

###

GET  http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/6628fa27dadb80391f06e6b0

###
DELETE http://localhost:3000/api/services/662a426cd5ae5034ea15bafa

###
PUT http://localhost:3000/api/services/662a423dd5ae5034ea15baf8
Content-Type: application/json

{
    "name": "TESTE ATUALIZAÇÃO",
    "description": "Algum descrição",
    "price": "2500",
    "image": "https://www.ifsc.edu.br/documents/1920563/3622212/ifsc_verifica_telemedicina-05.jpg/340b440f-8dbe-400b-b61c-dfbcd7b1983d?t=1632854865119"
}